# Generated by Django 6.0.7 on 2026-07-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Loyiha nomi')),
                ('description', models.TextField(verbose_name='Loyiha haqida qisqacha matn')),
                ('technologies', models.CharField(max_length=200, verbose_name='Ishlatilgan texnologiyalar (vergul bilan ajrating)')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Loyiha havolasi (link)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Loyiha rasmi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Loyiha',
                'verbose_name_plural': 'Loyihalar',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ko'nikma nomi")),
                ('percentage', models.IntegerField(verbose_name='Bilish darajasi (%)')),
            ],
            options={
                'verbose_name': "Ko'nikma",
                'verbose_name_plural': "Ko'nikmalar",
            },
        ),
    ]
